
import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Readdy Site",
  description: "Generated by Readdy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} antialiased`}
      >
        <header className="bg-white shadow-sm sticky top-0 z-50">
          <nav className="max-w-7xl mx-auto px-6 py-4">
            <div className="flex items-center justify-between">
              <Link href="/" className="text-2xl font-[\\\'Pacifico\\\'] text-amber-600">
                logo
              </Link>
              <div className="hidden md:flex space-x-8">
                <Link href="/" className="text-gray-700 hover:text-amber-600 transition-colors cursor-pointer">
                  首页
                </Link>
                <Link href="/services" className="text-gray-700 hover:text-amber-600 transition-colors cursor-pointer">
                  服务项目
                </Link>
                <Link href="/cases" className="text-gray-700 hover:text-amber-600 transition-colors cursor-pointer">
                  成功案例
                </Link>
                <Link href="/tools" className="text-gray-700 hover:text-amber-600 transition-colors cursor-pointer">
                  专业工具
                </Link>
                <Link href="/about" className="text-gray-700 hover:text-amber-600 transition-colors cursor-pointer">
                  关于我们
                </Link>
                <Link href="/consultation" className="bg-amber-600 hover:bg-amber-700 text-white px-4 py-2 rounded-lg transition-colors cursor-pointer whitespace-nowrap">
                  预约咨询
                </Link>
              </div>
              <button className="md:hidden text-gray-700">
                <i className="ri-menu-line text-xl"></i>
              </button>
            </div>
          </nav>
        </header>
        {children}
        <footer className="bg-gray-900 text-white py-16">
          <div className="max-w-7xl mx-auto px-6">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-8 mb-8">
              <div>
                <div className="text-2xl font-[\\\'Pacifico\\\'] text-amber-400 mb-4">logo</div>
                <p className="text-gray-400 text-sm leading-relaxed">
                  融合国学智慧与现代专业，致力于为高净值家族提供全方位财富传承解决方案。
                </p>
              </div>
              <div>
                <h3 className="font-semibold mb-4">服务项目</h3>
                <ul className="space-y-2 text-sm text-gray-400">
                  <li><Link href="/services" className="hover:text-amber-400 transition-colors cursor-pointer">财富规划设计</Link></li>
                  <li><Link href="/services" className="hover:text-amber-400 transition-colors cursor-pointer">税务筹划优化</Link></li>
                  <li><Link href="/services" className="hover:text-amber-400 transition-colors cursor-pointer">家族传承架构</Link></li>
                  <li><Link href="/services" className="hover:text-amber-400 transition-colors cursor-pointer">家庭教育指导</Link></li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold mb-4">资源中心</h3>
                <ul className="space-y-2 text-sm text-gray-400">
                  <li><Link href="/tools" className="hover:text-amber-400 transition-colors cursor-pointer">专业工具</Link></li>
                  <li><Link href="/cases" className="hover:text-amber-400 transition-colors cursor-pointer">成功案例</Link></li>
                  <li><Link href="/about" className="hover:text-amber-400 transition-colors cursor-pointer">关于我们</Link></li>
                  <li><Link href="/consultation" className="hover:text-amber-400 transition-colors cursor-pointer">预约咨询</Link></li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold mb-4">联系我们</h3>
                <div className="space-y-2 text-sm text-gray-400">
                  <div className="flex items-center">
                    <i className="ri-phone-line mr-2"></i>
                    400-888-6688
                  </div>
                  <div className="flex items-center">
                    <i className="ri-mail-line mr-2"></i>
                    info@wealthplanner.com
                  </div>
                  <div className="flex items-center">
                    <i className="ri-map-pin-line mr-2"></i>
                    上海市浦东新区陆家嘴
                  </div>
                </div>
              </div>
            </div>
            <div className="border-t border-gray-800 pt-8 text-center text-gray-400 text-sm">
              2024 智慧财富传承. All rights reserved.
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
